---
- name: converge
  hosts: all
  become: yes
  gather_facts: yes

  roles:
    - role: ansible-role-cron
      cron_jobs:
        - name: requested job
          job: "ls -alh > /dev/null"
          user: "cron"
        - name: requested job by the minute
          minute: "23"
          job: "ls -alh > /dev/null"
